-- AlterTable
ALTER TABLE "Account" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "UpdatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Customer" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "UpdatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Employee" ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "UpdatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Loan" ADD COLUMN     "UpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "StartDate" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "LoanPayment" ADD COLUMN     "CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "UpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Notification" ALTER COLUMN "PublishedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CreatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "UpdatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Transaction" ADD COLUMN     "CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "UpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
