version: '3'
services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - app

  # app:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./app:/app
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5436:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "postgres", "-d", "midshiftDB"]
      interval: 5s
      timeout: 10s
      retries: 5
      
volumes:
  pgdata: {}